name: cbnew-push

on:
  schedule:
    # 每工作日9:00执行
    - cron: '0 9 * * 1-5'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
          ref: master

    - name: Run cbnew push job
      run: |
        sudo bin/cbnew ${{ secrets.BARK_KEY }}
